server:
  port: 9000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ADMIN-SERVICE
          uri: http://localhost:8081/
          predicates:
            - Path=/admins/**
        - id: ORDER-SERVICE
          uri: http://localhost:8082/
          predicates:
            - Path=/orders/**
        - id: USER-SERVICE
          uri: http://localhost:8083/
          predicates:
            - Path=/users/**
        - id: WASHER-SERVICE
          uri: http://localhost:8085/
          predicates:
            - Path=/washers/**
