server:
  port: 9000


spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ADMIN-SERVICE
          uri: http://localhost:8081/
          predicate:
            - Path=/admin/**